[package]
name = "shared"
version = "0.1.0"
authors = ["MÃ¨ir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = ">=0.14"
rtbvh = { path = "../" }
bvh = "0.5"
